from django.contrib import admin
from .models import AutodeskConstructionCloudProject, AutodeskConstructionCloudReport

admin.site.register(AutodeskConstructionCloudProject)
admin.site.register(AutodeskConstructionCloudReport)