databases:
  - name: GTAInfralignDB
    plan: free
    databaseName: GTAInfralign
    user: GTAInfralign

services:
  - type: web
    plan: free
    name: GTAInfralign
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn infralign.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: GTAInfralignDB
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4