name: Django Testing
on:
  pull_request:
    branches:
    - main
  workflow_call:

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with unittest
        run: |
          python manage.py migrate
          python manage.py test
        env:
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_PORT: 5432
          DB_NAME: postgres
          SECRET_KEY: verysecret