name: Production Testing and Deployment
on:
  push:
    branches:
      - main

jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.x'
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Test with unittest
          run: |
            python manage.py migrate
            python manage.py test
  deployment:
    name: Deployment
    needs: testing
    runs-on: ubuntu-latest
    steps:
      - name: Run Deploy Hook
        env:
          DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: curl "$DEPLOY_HOOK"
