name: Production Testing and Deployment
on:
  push:
    branches:
      - main

jobs:
  testing:
    uses: tris-g/GTAInfralign/.github/workflows/django_test.yaml@main
  deployment:
    name: Deployment
    needs: testing
    runs-on: ubuntu-latest
    steps:
      - name: Run Deploy Hook
        env:
          DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: curl "$DEPLOY_HOOK"
